server:
  port: 8080
spring:
  datasource:
    test1:
      jdbcUrl: jdbc:mysql://localhost:3306/test001?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: qwer1234!!
      driver-class-name: com.mysql.cj.jdbc.Driver
    test2:
      jdbcUrl: jdbc:mysql://localhost:3306/test002?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: qwer1234!!
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.multiple.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true